# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgprueba.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgPrueba(object):
    def setupUi(self, DlgPrueba):
        DlgPrueba.setObjectName("DlgPrueba")
        DlgPrueba.resize(400, 300)
        self.lineEdit = QtWidgets.QLineEdit(DlgPrueba)
        self.lineEdit.setGeometry(QtCore.QRect(80, 90, 221, 71))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(DlgPrueba)
        QtCore.QMetaObject.connectSlotsByName(DlgPrueba)

    def retranslateUi(self, DlgPrueba):
        _translate = QtCore.QCoreApplication.translate
        DlgPrueba.setWindowTitle(_translate("DlgPrueba", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DlgPrueba = QtWidgets.QDialog()
    ui = Ui_DlgPrueba()
    ui.setupUi(DlgPrueba)
    DlgPrueba.show()
    sys.exit(app.exec_())
