# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(305, 384)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblGeneradorNro = QtWidgets.QLabel(self.centralwidget)
        self.lblGeneradorNro.setGeometry(QtCore.QRect(100, 10, 101, 20))
        self.lblGeneradorNro.setMaximumSize(QtCore.QSize(101, 16777215))
        self.lblGeneradorNro.setObjectName("lblGeneradorNro")
        self.cmbGeneradorNros = QtWidgets.QComboBox(self.centralwidget)
        self.cmbGeneradorNros.setGeometry(QtCore.QRect(30, 40, 231, 22))
        self.cmbGeneradorNros.setObjectName("cmbGeneradorNros")
        self.cmbGeneradorNros.addItem("")
        self.cmbGeneradorNros.addItem("")
        self.cmbGeneradorNros.addItem("")
        self.cmbIntervalos = QtWidgets.QComboBox(self.centralwidget)
        self.cmbIntervalos.setGeometry(QtCore.QRect(20, 240, 251, 22))
        self.cmbIntervalos.setObjectName("cmbIntervalos")
        self.cmbIntervalos.addItem("")
        self.cmbIntervalos.addItem("")
        self.cmbIntervalos.addItem("")
        self.cmbIntervalos.addItem("")
        self.IntervalosLabel = QtWidgets.QLabel(self.centralwidget)
        self.IntervalosLabel.setGeometry(QtCore.QRect(120, 220, 71, 16))
        self.IntervalosLabel.setObjectName("IntervalosLabel")
        self.semillaLabel = QtWidgets.QLabel(self.centralwidget)
        self.semillaLabel.setGeometry(QtCore.QRect(60, 280, 47, 13))
        self.semillaLabel.setObjectName("semillaLabel")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(50, 80, 191, 121))
        self.groupBox.setObjectName("groupBox")
        self.gLabel = QtWidgets.QLabel(self.groupBox)
        self.gLabel.setGeometry(QtCore.QRect(20, 50, 47, 13))
        self.gLabel.setObjectName("gLabel")
        self.kLabel = QtWidgets.QLabel(self.groupBox)
        self.kLabel.setGeometry(QtCore.QRect(20, 80, 47, 13))
        self.kLabel.setObjectName("kLabel")
        self.cLabel = QtWidgets.QLabel(self.groupBox)
        self.cLabel.setGeometry(QtCore.QRect(20, 20, 47, 13))
        self.cLabel.setObjectName("cLabel")
        self.kBox = QtWidgets.QSpinBox(self.groupBox)
        self.kBox.setGeometry(QtCore.QRect(90, 80, 81, 22))
        self.kBox.setObjectName("kBox")
        self.gBox = QtWidgets.QSpinBox(self.groupBox)
        self.gBox.setGeometry(QtCore.QRect(90, 50, 81, 22))
        self.gBox.setObjectName("gBox")
        self.cBox = QtWidgets.QSpinBox(self.groupBox)
        self.cBox.setGeometry(QtCore.QRect(90, 20, 81, 22))
        self.cBox.setObjectName("cBox")
        self.btnAceptar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAceptar.setGeometry(QtCore.QRect(60, 350, 75, 23))
        self.btnAceptar.setObjectName("btnAceptar")
        self.btnCancelar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancelar.setGeometry(QtCore.QRect(160, 350, 75, 23))
        self.btnCancelar.setObjectName("btnCancelar")
        self.semillaBox = QtWidgets.QSpinBox(self.centralwidget)
        self.semillaBox.setGeometry(QtCore.QRect(140, 280, 81, 22))
        self.semillaBox.setObjectName("semillaBox")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblGeneradorNro.setText(_translate("MainWindow", "Generador de Nros"))
        self.cmbGeneradorNros.setItemText(0, _translate("MainWindow", "Congruencial Lineal"))
        self.cmbGeneradorNros.setItemText(1, _translate("MainWindow", "Congruencial Multiplicativo"))
        self.cmbGeneradorNros.setItemText(2, _translate("MainWindow", "Funcion del lenguaje utilizado"))
        self.cmbIntervalos.setItemText(0, _translate("MainWindow", "5"))
        self.cmbIntervalos.setItemText(1, _translate("MainWindow", "10"))
        self.cmbIntervalos.setItemText(2, _translate("MainWindow", "15"))
        self.cmbIntervalos.setItemText(3, _translate("MainWindow", "20"))
        self.IntervalosLabel.setText(_translate("MainWindow", "Intervalos"))
        self.semillaLabel.setText(_translate("MainWindow", "semilla"))
        self.groupBox.setTitle(_translate("MainWindow", "Constantes"))
        self.gLabel.setText(_translate("MainWindow", "g"))
        self.kLabel.setText(_translate("MainWindow", "k"))
        self.cLabel.setText(_translate("MainWindow", "c"))
        self.btnAceptar.setText(_translate("MainWindow", "Aceptar"))
        self.btnCancelar.setText(_translate("MainWindow", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
