# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'secondView.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem


class Ui_SecondViewWindow(object):
    def setupUi(self, SecondViewWindow):
        SecondViewWindow.setObjectName("SecondViewWindow")
        SecondViewWindow.resize(826, 662)
        self.centralwidget = QtWidgets.QWidget(SecondViewWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.resultLbl = QtWidgets.QLabel(self.centralwidget)
        self.resultLbl.setGeometry(QtCore.QRect(600, 10, 61, 16))
        self.resultLbl.setObjectName("resultLbl")
        self.histogramaLbl = QtWidgets.QLabel(self.centralwidget)
        self.histogramaLbl.setGeometry(QtCore.QRect(200, 0, 101, 31))
        self.histogramaLbl.setObjectName("histogramaLbl")
        self.histogramaTable = QtWidgets.QGraphicsView(self.centralwidget)
        self.histogramaTable.setGeometry(QtCore.QRect(50, 30, 371, 251))
        self.histogramaTable.setObjectName("histogramaTable")
        self.JiCuadradoBox = QtWidgets.QSpinBox(self.centralwidget)
        self.JiCuadradoBox.setGeometry(QtCore.QRect(530, 590, 131, 22))
        self.JiCuadradoBox.setObjectName("JiCuadradoBox")
        self.jcTitleLbl = QtWidgets.QLabel(self.centralwidget)
        self.jcTitleLbl.setGeometry(QtCore.QRect(350, 300, 171, 16))
        self.jcTitleLbl.setObjectName("jcTitleLbl")
        self.JcLbl = QtWidgets.QLabel(self.centralwidget)
        self.JcLbl.setGeometry(QtCore.QRect(460, 590, 61, 16))
        self.JcLbl.setObjectName("JcLbl")
        self.return_2 = QtWidgets.QPushButton(self.centralwidget)
        self.return_2.setGeometry(QtCore.QRect(30, 610, 221, 23))
        self.return_2.setObjectName("return_2")
        self.resultTable = QtWidgets.QTableWidget(self.centralwidget)
        self.resultTable.setGeometry(QtCore.QRect(440, 30, 371, 251))
        self.resultTable.setObjectName("resultTable")
        self.resultTable.setColumnCount(4)

        #aca estan los rows
        self.resultTable.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable.setHorizontalHeaderItem(3, item)

        self.resultTable.horizontalHeader().setVisible(True)
        self.resultTable.horizontalHeader().setCascadingSectionResizes(False)
        self.resultTable.horizontalHeader().setDefaultSectionSize(92)
        self.resultTable.horizontalHeader().setHighlightSections(True)
        self.resultTable.horizontalHeader().setSortIndicatorShown(False)
        self.resultTable.verticalHeader().setVisible(False)
        self.resultTable.verticalHeader().setDefaultSectionSize(20)
        self.jiCuadradoTable = QtWidgets.QTableWidget(self.centralwidget)
        self.jiCuadradoTable.setGeometry(QtCore.QRect(140, 330, 581, 251))
        self.jiCuadradoTable.setObjectName("jiCuadradoTable")
        self.jiCuadradoTable.setColumnCount(5)
        self.jiCuadradoTable.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.jiCuadradoTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.jiCuadradoTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.jiCuadradoTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.jiCuadradoTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.jiCuadradoTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.jiCuadradoTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.jiCuadradoTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.jiCuadradoTable.setHorizontalHeaderItem(4, item)
        self.jiCuadradoTable.horizontalHeader().setDefaultSectionSize(115)
        self.jiCuadradoTable.verticalHeader().setVisible(False)
        SecondViewWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SecondViewWindow)
        self.statusbar.setObjectName("statusbar")
        SecondViewWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SecondViewWindow)
        QtCore.QMetaObject.connectSlotsByName(SecondViewWindow)

    def retranslateUi(self, SecondViewWindow):
        _translate = QtCore.QCoreApplication.translate
        SecondViewWindow.setWindowTitle(_translate("SecondViewWindow", "MainWindow"))
        self.resultLbl.setText(_translate("SecondViewWindow", "Resultados"))
        self.histogramaLbl.setText(_translate("SecondViewWindow", "Histograma"))
        self.jcTitleLbl.setText(_translate("SecondViewWindow", "Prueba de Bondad con Ji Cuadrado"))
        self.JcLbl.setText(_translate("SecondViewWindow", "Ji Calculado"))
        self.return_2.setText(_translate("SecondViewWindow", "Return"))

        #traslado de tabla
        item = self.resultTable.verticalHeaderItem(0)
        item.setText(_translate("SecondViewWindow", "1"))
        item = self.resultTable.verticalHeaderItem(1)
        item.setText(_translate("SecondViewWindow", "2"))
        item = self.resultTable.verticalHeaderItem(2)
        item.setText(_translate("SecondViewWindow", "3"))
        item = self.resultTable.horizontalHeaderItem(0)
        item.setText(_translate("SecondViewWindow", "i"))
        item = self.resultTable.horizontalHeaderItem(1)
        item.setText(_translate("SecondViewWindow", "(a.X +c)"))
        item = self.resultTable.horizontalHeaderItem(2)
        item.setText(_translate("SecondViewWindow", "Xi+1"))
        item = self.resultTable.horizontalHeaderItem(3)
        item.setText(_translate("SecondViewWindow", "RND"))
        item = self.jiCuadradoTable.verticalHeaderItem(0)
        item.setText(_translate("SecondViewWindow", "1"))
        item = self.jiCuadradoTable.verticalHeaderItem(1)
        item.setText(_translate("SecondViewWindow", "2"))
        item = self.jiCuadradoTable.verticalHeaderItem(2)
        item.setText(_translate("SecondViewWindow", "3"))
        item = self.jiCuadradoTable.horizontalHeaderItem(0)
        item.setText(_translate("SecondViewWindow", "Intervalo"))
        item = self.jiCuadradoTable.horizontalHeaderItem(1)
        item.setText(_translate("SecondViewWindow", "fo"))
        item = self.jiCuadradoTable.horizontalHeaderItem(2)
        item.setText(_translate("SecondViewWindow", "fe"))
        item = self.jiCuadradoTable.horizontalHeaderItem(3)
        item.setText(_translate("SecondViewWindow", "C"))
        item = self.jiCuadradoTable.horizontalHeaderItem(4)
        item.setText(_translate("SecondViewWindow", "C(AC)"))

    def cargar_tabla_resultados(self, matriz):
        rowPosition = self.resultTable.rowCount()
        self.resultTable.clear()
        self.resultTable.setColumnCount(4)
        self.resultTable.setRowCount(len(matriz))
        
        for i in range(len(matriz)):
            item = QtWidgets.QTableWidgetItem()
            self.resultTable.setVerticalHeaderItem(i, item)

            #self.resultTable.insertRow(rowPosition)
            #self.resultTable.setItem(rowPosition , 0, QTableWidgetItem("text1"))
            ##oso = str(matriz[i][0])
            #self.resultTable.setItem(rowPosition , 1, QTableWidgetItem("text1"))
            #self.resultTable.setItem(rowPosition , 2, QTableWidgetItem("text1"))
            #self.resultTable.setItem(rowPosition , 3, QTableWidgetItem("text1"))
            #rowPosition = self.resultTable.rowCount()
            #rowPosition += 1
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SecondViewWindow = QtWidgets.QMainWindow()
    ui = Ui_SecondViewWindow()
    ui.setupUi(SecondViewWindow)
    SecondViewWindow.show()
    sys.exit(app.exec_())
