# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(305, 384)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblGeneradorNro = QtWidgets.QLabel(self.centralwidget)
        self.lblGeneradorNro.setGeometry(QtCore.QRect(90, 20, 101, 16))
        self.lblGeneradorNro.setMaximumSize(QtCore.QSize(101, 16777215))
        self.lblGeneradorNro.setObjectName("lblGeneradorNro")
        self.cmbGeneradorNros = QtWidgets.QComboBox(self.centralwidget)
        self.cmbGeneradorNros.setGeometry(QtCore.QRect(30, 40, 231, 22))
        self.cmbGeneradorNros.setObjectName("cmbGeneradorNros")
        self.cmbIntervalos = QtWidgets.QComboBox(self.centralwidget)
        self.cmbIntervalos.setGeometry(QtCore.QRect(20, 240, 251, 22))
        self.cmbIntervalos.setObjectName("cmbIntervalos")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(120, 220, 71, 16))
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 280, 47, 13))
        self.label_5.setObjectName("label_5")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(50, 80, 191, 121))
        self.groupBox.setObjectName("groupBox")
        self.txtG = QtWidgets.QTextEdit(self.groupBox)
        self.txtG.setGeometry(QtCore.QRect(100, 50, 81, 21))
        self.txtG.setObjectName("txtG")
        self.txtK = QtWidgets.QTextEdit(self.groupBox)
        self.txtK.setGeometry(QtCore.QRect(100, 80, 81, 21))
        self.txtK.setObjectName("txtK")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 47, 13))
        self.label_3.setObjectName("label_3")
        self.txtC = QtWidgets.QTextEdit(self.groupBox)
        self.txtC.setEnabled(True)
        self.txtC.setGeometry(QtCore.QRect(100, 20, 81, 21))
        self.txtC.setReadOnly(False)
        self.txtC.setObjectName("txtC")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 47, 13))
        self.label_4.setObjectName("label_4")
        self.txtSemilla = QtWidgets.QTextEdit(self.centralwidget)
        self.txtSemilla.setGeometry(QtCore.QRect(140, 280, 104, 21))
        self.txtSemilla.setObjectName("txtSemilla")
        self.btnAceptar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAceptar.setGeometry(QtCore.QRect(60, 350, 75, 23))
        self.btnAceptar.setObjectName("btnAceptar")
        self.btnCancelar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancelar.setGeometry(QtCore.QRect(160, 350, 75, 23))
        self.btnCancelar.setObjectName("btnCancelar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblGeneradorNro.setText(_translate("MainWindow", "Generador de Nros"))
        self.label_6.setText(_translate("MainWindow", "Intervalos"))
        self.label_5.setText(_translate("MainWindow", "semilla"))
        self.groupBox.setTitle(_translate("MainWindow", "Constantes"))
        self.label_2.setText(_translate("MainWindow", "g"))
        self.label_3.setText(_translate("MainWindow", "k"))
        self.label_4.setText(_translate("MainWindow", "c"))
        self.btnAceptar.setText(_translate("MainWindow", "Aceptar"))
        self.btnCancelar.setText(_translate("MainWindow", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
